<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>	
	<parent>
		<groupId>jonathan.home</groupId>
		<artifactId>rest-api-project</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

    <artifactId>openapi_defintion</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Spring server dependencies -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-models</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>

        <!-- These are required for client java code generation -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gsonfire</groupId>
            <artifactId>gson-fire</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.25.0</version>
                <executions>
                    <execution>
                        <id>SpringServer</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.baseUri}/src/main/resources/api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
							<apiPackage>jonathan.home.api</apiPackage>
							<modelPackage>jonathan.home.model</modelPackage>
							<generateModelDocumentation>true</generateModelDocumentation>
							<supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <ignoreFileOverride>${project.basedir}/.openapi-generator-ignore</ignoreFileOverride>
                            <configOptions>
                                <reactive>false</reactive>
							    <useSpringBoot4>true</useSpringBoot4>
                                <!-- Setting useTags flag will generate a new API file for each tag as defined in the yaml.
                                With a default api file for any that don't have a tag -->
                                <useTags>true</useTags>
								<dateLibrary>java8</dateLibrary>
								<interfaceOnly>true</interfaceOnly>
								<delegatePattern>true</delegatePattern>
								<useSpringController>true</useSpringController>
								<useSwaggerUI>true</useSwaggerUI>
								<legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
								<useOneOfInterfaces>true</useOneOfInterfaces>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>ReactiveSpringServer</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.baseUri}/src/main/resources/reactiveapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>jonathan.home.reactiveapi</apiPackage>
                            <modelPackage>jonathan.home.model</modelPackage>
                            <generateModelDocumentation>true</generateModelDocumentation>
                            <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
                            <configOptions>
                                <!-- reactive to use Mono/Flux. useResponseEntity to avoid wrapping all results in Mono<> -->
                                <reactive>true</reactive>
                                <useResponseEntity>false</useResponseEntity>
                                <useSpringBoot4>true</useSpringBoot4>
                                <dateLibrary>java8</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                                <delegatePattern>true</delegatePattern>
                                <useSpringController>true</useSpringController>
                                <useSwaggerUI>true</useSwaggerUI>
                                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                            </configOptions>
                        </configuration>
                    </execution>
                    <execution>
                        <id>PythonClient</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.baseUri}/src/main/resources/api.yaml</inputSpec>
                            <generatorName>python</generatorName>
                            <configOptions>
                                <generateSourceCodeOnly>true</generateSourceCodeOnly>
                                <useOneOfDiscriminatorLookup>true</useOneOfDiscriminatorLookup>
                            </configOptions>
                            <output>${project.basedir}/../../python/api</output>
                        </configuration>
                    </execution>
                    <execution>
                        <id>CSharp</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.baseUri}/src/main/resources/api.yaml</inputSpec>
                            <generatorName>csharp</generatorName>
                            <configOptions>
                                <useOneOfDiscriminatorLookup>false</useOneOfDiscriminatorLookup>
                                <targetFramework>netstandard2.1</targetFramework>
                            </configOptions>
                            <output>${project.basedir}/../../csharp/api</output>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>